# Generated by Django 6.0.1 on 2026-02-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
                ('biography', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='director_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=25)),
                ('duration', models.IntegerField()),
                ('year', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='movie_pictures/')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='Movies.director')),
            ],
        ),
    ]
